### ISSUE TITLE
Project roadmap

### ISSUE THREAD

**Issue by FoilHatGuy** [Feersys/Learning-python#6]
## Server creation 
- [x] basics #3 
- [ ] Methods #4 
- [ ] Response codes #4 
- [ ] Handle different body types #4 

## Python
- [ ] typing (типизирование) #8 
  - [ ] Models
  - [ ] Validation

- [ ] Functions
- [ ] Classes
  - [ ] Basics
  - [ ] Inheritance (наследование)
  - [ ] static methods
- [ ] Storing data
  - [ ] pandas
  - [ ] File System 
  - [ ] PostgreSQL
- [ ] Packages
- [ ] Configs
  - [ ] constants
  - [ ] Environment variables (переменные среды)
  - [ ] Flags
  - [ ] From file
   
- [x] pip install etc.
- [ ] Build .exe
- [ ] Math stuff
  - [ ] numpy
  - [ ] matplotlib

## Postgres
- [ ] Tables
- [ ] Foreign keys (ключи для связки двух таблиц)
- [ ] Query syntax (синтаксис запросов)
- [ ] Index
- [ ] ENUM

## RegEx
- [ ] change variable cases (snake_case, camelCase, kebab-case)
  - [ ] Auto input type
  - [ ] universal function
